const key = "categoryTypes";

const CATEGORY_GET_LIST_SUCCESS = `${key}/CATEGORY_GET_LIST_SUCCESS`;
const CATEGORY_GET_LIST_FAILED = `${key}/CATEGORY_GET_LIST_FAILED`;
const CATEGORY_GET_LIST = `${key}/CATEGORY_GET_LIST`;

const CATEGORY_CREATE_SUCCESS = `${key}/CATEGORY_CREATE_SUCCESS`;
const CATEGORY_CREATE_FAILED = `${key}/CATEGORY_CREATE_FAILED`;
const CATEGORY_CREATE = `${key}/CATEGORY_CREATE`;

const DEPARTMENT_GET_LIST_SUCCESS = `${key}/DEPARTMENT_GET_LIST_SUCCESS`;
const DEPARTMENT_GET_LIST_FAILED = `${key}/DEPARTMENT_GET_LIST_FAILED`;
const DEPARTMENT_GET_LIST = `${key}/DEPARTMENT_GET_LIST`;

const CATEGORY_DELETE_SUCCESS = `${key}/CATEGORY_DELETE_SUCCESS`;
const CATEGORY_DELETE_FAILED = `${key}/CATEGORY_DELETE_FAILED`;
const CATEGORY_DELETE = `${key}/CATEGORY_DELETE`;
const CATEGORY_DELETE_FROM_STATE = `${key}/CATEGORY_DELETE_FROM_STATE`;

export {
  CATEGORY_GET_LIST_SUCCESS,
  CATEGORY_GET_LIST_FAILED,
  CATEGORY_GET_LIST,
  DEPARTMENT_GET_LIST_FAILED,
  DEPARTMENT_GET_LIST,
  DEPARTMENT_GET_LIST_SUCCESS,
  CATEGORY_CREATE,
  CATEGORY_CREATE_FAILED,
  CATEGORY_CREATE_SUCCESS,
  CATEGORY_DELETE,
  CATEGORY_DELETE_FAILED,
  CATEGORY_DELETE_SUCCESS,
  CATEGORY_DELETE_FROM_STATE,
};
