const key = "closureDateTypes";

const CLOSURE_DATE_GET_LIST_SUCCESS = `${key}/CLOSURE_DATE_GET_LIST_SUCCESS`;
const CLOSURE_DATE_GET_LIST_FAILED = `${key}/CLOSURE_DATE_GET_LIST_FAILED`;
const CLOSURE_DATE_GET_LIST = `${key}/CLOSURE_DATE_GET_LIST`;

export {
  CLOSURE_DATE_GET_LIST_SUCCESS,
  CLOSURE_DATE_GET_LIST_FAILED,
  CLOSURE_DATE_GET_LIST,
};
