const key = "globalTypes";

const SHOW_SIDEBAR = `${key}/SHOW_SIDEBAR`;
const HIDE_SIDEBAR = `${key}/HIDE_SIDEBAR`;

const SHOW_MODAL = `${key}/SHOW_MODAL`;
const HIDE_MODAL = `${key}/HIDE_MODAL`;

const ROLE_GET_LIST_SUCCESS = `${key}/ROLE_GET_LIST_SUCCESS`;
const ROLE_GET_LIST_FAILED = `${key}/ROLE_GET_LIST_FAILED`;
const ROLE_GET_LIST = `${key}/ROLE_GET_LIST`;

export {
  SHOW_SIDEBAR,
  HIDE_SIDEBAR,
  SHOW_MODAL,
  HIDE_MODAL,
  ROLE_GET_LIST,
  ROLE_GET_LIST_FAILED,
  ROLE_GET_LIST_SUCCESS,
};
