const key = "ideaTypes";

const IDEA_GET_LIST_SUCCESS = `${key}/IDEA_GET_LIST_SUCCESS`;
const IDEA_GET_LIST_FAILED = `${key}/IDEA_GET_LIST_FAILED`;
const IDEA_GET_LIST = `${key}/IDEA_GET_LIST`;

const IDEA_GET_DETAIL_SUCCESS = `${key}/IDEA_GET_DETAIL_SUCCESS`;
const IDEA_GET_DETAIL_FAILED = `${key}/IDEA_GET_DETAIL_FAILED`;
const IDEA_GET_DETAIL = `${key}/IDEA_GET_DETAIL`;

export {
  IDEA_GET_LIST_SUCCESS,
  IDEA_GET_LIST_FAILED,
  IDEA_GET_LIST,
  IDEA_GET_DETAIL_SUCCESS,
  IDEA_GET_DETAIL_FAILED,
  IDEA_GET_DETAIL,
};
